name: Python package av-tweet-ingestion CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
  S3_ACESS_KEY: ${{ secrets.S3_ACESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  S3_LANDING_LAYER: ${{ secrets.S3_LANDING_LAYER }}
  PYPI_API_USER: ${{ secrets.PYPI_API_USER }}
  PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  test-deploy:

    runs-on: ubuntu-latest
    environment: env
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.1     
    - name: Install dependencies
      run: |
        make install
    - name: Run tests
      run: |
        make test
    - name: Install build dependencies
      run: |
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: ${{ env.PYPI_API_USER }}
        password: ${{ env.PYPI_API_TOKEN }}