name: Python package av-tweet-ingestion CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
  S3_ACESS_KEY: ${{ secrets.S3_ACESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  S3_LANDING_LAYER: ${{ secrets.S3_LANDING_LAYER }}
  TEST_ENV_VAR: my-env-var-test
  TEST_ENV_VAR_SECRETS: ${{ secrets.TEST_ENV_VAR_SECRETS }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.1     
    - name: Install dependencies
      run: |
        make install
    - name: echo var1
      run: echo $TEST_ENV_VAR
    - name: echo var2
      run: echo $TEST_ENV_VAR_SECRETS
    - name: Run tests
      run: |
        make test
